version: 1
abstractStyle: '30'
firstLineAbstract: 'false'
enableFlexibleHeight: 'false'
noteHeight: '30'
notePosition: 'side-top'
abstractPosition: 'before-labels'
fontColor: '#525252'
backgroundColor: '#FFFF99'
fontSize: 'default'
enableNoteFontBold: 'false'
abstractFontColor: '#525252'
abstractBackgroundColor: '#FFFF99'
abstractFontSize: 'default'
printFontSize: 'default'
sidebarWidth: '300px'
usePopForLogin: 'false'
showConnectionPrompt: 'false'
showAddCalendar: 'false'
showDelete: 'false'
showNoteColorPicker: 'false'
showNoteHistory: 'false'
showAbstractBracket: 'true'
enableNoDisturbMode: 'false'
enableRichtextEditor: 'false'
showPrintingNote: 'true'
showSavingStatus: 'true'
showNoteTimeStamp: 'true'
noteFolderName: '_SIMPLE_GMAIL_NOTES_'
disableConsecutiveWarning: 'false'
searchInhome: 'true'
showCRMButton: 'true'
showCRMSuccessPage: 'true'
subscriptionEmail: 'john.bullock@gmail.com'
showLogo: 'false'
useAdvancedColors: 'true'
usefontColors: 'false'
useCustomGoogleDrivefolder: ''
hideTextAreaForBlankNotes: 'false'
templateContent: ''
templateAutoload: 'false'
disabledAccounts: '[]'
